services:
  - type: web
    name: n8n
    env: docker
    image:
      url: n8nio/n8n:latest
    healthCheckPath: /healthz
    envVars:
      - key: DATABASE_URL
        fromService:
          type: pserv
          name: n8n-db
          property: connectionString
      - key: N8N_CUSTOM_EXTENSIONS
        value: n8n-nodes-comfyui

databases:
  - name: n8n-db
    databaseName: n8n
    user: n8n_user
    plan: free
