services:
  - type: web
    name: n8n
    env: docker
    image:
      url: n8nio/n8n:latest
    healthCheckPath: /healthz
    envVars:
      - key: DB_TYPE
        value: postgresdb
      - key: DB_POSTGRESDB_HOST
        fromService:
          type: pserv
          name: n8n-db
          property: host
      - key: DB_POSTGRESDB_DATABASE
        fromService:
          type: pserv
          name: n8n-db
          property: database
      - key: DB_POSTGRESDB_USER
        fromService:
          type: pserv
          name: n8n-db
          property: user
      - key: DB_POSTGRESDB_PASSWORD
        fromService:
          type: pserv
          name: n8n-db
          property: password
      - key: N8N_CUSTOM_EXTENSIONS
        value: n8n-nodes-comfyui

databases:
  - name: n8n-db
    databaseName: n8n
    user: n8n_user
    plan: free
